### ISSUE TITLE
[BUG] Change Error Message When Invite User And Type Any `URL` 

### ISSUE THREAD

**Issue by yousef-genedy** [TutTrue/reboard#1]
## Description
When creating a board with members, and invite someone, it works good when typing the `github username` only. Need to handle the error messages of other typed text.

The error message says the following:
> **ERROR**
>  Invalid board name, name can't contain spaces.

But there is actually no spaces.

### Typing github `url`
![image](https://github.com/TutTrue/reboard/assets/115221628/898e0572-7473-426e-b166-4cac4534b57d)

### Typing any `url`
![image](https://github.com/TutTrue/reboard/assets/115221628/90db122b-2d52-4ba4-a511-c74fcfe48ce7)

**Comment by TutTrue** [comment]
we are using username not a url
